apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-backup
  namespace: cryo
  labels:
    go-cryo.github.com/config: "true"
data:
  config: |
    type: psql
    schedule: "0 2 * * *"
    repositoryRef: "cryo/my-repo"
    psql:
      hostname: postgres.production.svc.cluster.local
      port: 5432
      username: app_user
      database: my_application
    retention:
      keepLast: 7
      keepDaily: 30
      keepWeekly: 12
      keepMonthly: 6
