apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-s3-credentials
  namespace: cryo
type: Opaque
stringData:
  accessKey: "AKIAIOSFODNN7EXAMPLE"
  secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
