apiVersion: v1
kind: Secret
metadata:
  name: my-rest-host
  namespace: cryo
  labels:
    go-cryo.github.com/repository-host: "true"
type: Opaque
stringData:
  BASE_URL: "rest:https://backup.example.com"
