apiVersion: v1
kind: Secret
metadata:
  name: my-s3-host
  namespace: cryo
  labels:
    go-cryo.github.com/repository-host: "true"
type: Opaque
stringData:
  BASE_URL: "s3:https://my-bucket.s3.eu-central-1.amazonaws.com"
  AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
  AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  AWS_DEFAULT_REGION: "eu-central-1"
