apiVersion: v1
kind: Secret
metadata:
  name: my-s3-backup
  labels:
    go-cryo.github.com/repository: "true"
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:https://s3.amazonaws.com/my-bucket/path"
  RESTIC_PASSWORD: "my-restic-password"
  AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
  AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  AWS_DEFAULT_REGION: "eu-central-1"
